-- 코드를 작성해주세요
SELECT SUM(HG.SCORE) SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
    FROM HR_GRADE HG
    JOIN HR_EMPLOYEES HE
    ON HE.EMP_NO = HG.EMP_NO
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1;